version: '3.8'

services:
  bot:
    container_name: bot
    build: .
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: